### ISSUE TITLE
Clock sits on top of display when added to a screen saver

### ISSUE THREAD

**Issue by bfbad** [MichaelDimmitt/Aerial_Desktop#17]
Expected Result - when selecting to show with clock, the clock sits as part of the desktop.

Actual Result - The clock sits on top of all windows.

![image](https://user-images.githubusercontent.com/4720618/29584238-1cb6c230-8751-11e7-97c0-ff28b9ca4dd7.png)
With this option selected, the clock is expected to be part of the desktop (similar to the label which appears in the bottom left corner.

The clock sits on top:

![image](https://user-images.githubusercontent.com/4720618/29584308-55e9b544-8751-11e7-8418-49510671fd48.png)

**Comment by MichaelDimmitt** [comment]
Wow, nice catch. Interesting issue!
Here is my effort to redefine the issue. 
aerial desktop stays in the background but the clock is not in the background it is in the foreground. This is because the clock checkbox is implemented by apple who is expecting the clock to show up on a screensaver not a desktop! 😨  

The real trouble is that since the clock is on the foreground you cant click through it. 😨 

But no worries, I'm game planning a fix at ruby jax open hacks meetup today! 🙂

**Comment by tenso2006** [comment]
It would be great to make the clock go away on click when a user clicks the clock.

**Comment by MichaelDimmitt** [comment]
@tenso2006, 😥  oooh 😥, Turns out since apple is controlling the clock adding a click function onto the clock would be a headache.
Challenging way I think id have to attempt to achieve an apple click function.
1. Put a system object on top of the particular apple clock. 
2. Or find some way to modify the code to add a feature... also very tough since probably a binary.<br> There is probably not a default to set to modify that binary.

However, <b>Positive</b> Turns out since apple is controlling the clock I should be able to toggle it on and off by using defaults similar to defaults use currently to automatically change screensavers; a quick fix of changing the defualts via a toggle button two clicks away, inside the current application, or inside menubar feature to toggle the clock. Should be a happy way to get rid of the clock when it is getting in the way or bring it back when you'd like a belligerent clock there.

@bfbad, 🎉  <b>Maybe it will be a feature instead of a bug!</b> 🍾  🎉

**Comment by MichaelDimmitt** [comment]
I dont see an easy solution till the menubar is released.

Shelving for now.
