### ISSUE TITLE
Make the screensaver spread out across multiple monitors

### ISSUE THREAD

**Issue by pawarvaibhav** [MichaelDimmitt/Aerial_Desktop#42]
I use 2 monitors + 1 laptop screen for work. 

It would be super cool to see the same video spanned across 3 monitors. Like one big mosiac.

**Comment by MichaelDimmitt** [comment]
Did not respond to this for a while because adding a new feature when the app was not working did not make sense. 

In the last stable operating system "Sierra" the behavior of the program would play the same background on each monitor. "High Sierra" and "Mojave" just a single small window (degreded implementation)

Making a mozaic is not something I will build.
The videos that are put on the screen are delegated to the aerial screensaver and apples screensaver engine.
